### ISSUE TITLE
New Feature - Sender Name

### ISSUE THREAD

**Issue by hew2702** [BenediktBergmann/PCF-Controls#94]
Please add the name of the sender to the text bubble, either from a custom "Sender Name" field on the SMS table or from the "Sender" activity party role.

**Comment by BenediktBergmann** [comment]
Thanks for the suggestion, @hew2702.
I would try to implement it so that one could add another field for the sender name, which would be a text field. This could then be filled with whatever is needed. Whether it comes from a user, contact, regarding object or any other place. Would that be okay for you?

**Comment by hew2702** [comment]
That sound great, thank you!

**Comment by BenediktBergmann** [comment]
This feature is implemented and will be shipped with the next release. I will create the next release within the next 2-3 days

**Comment by hew2702** [comment]
Fantastic, thank you so much!!

**Comment by BenediktBergmann** [comment]
New version (2.2.0.0) was just released.
