### ISSUE TITLE
PCF Not Updating On Bound Column Change

### ISSUE THREAD

**Issue by hew2702** [BenediktBergmann/PCF-Controls#97]
For the new filter feature, I have bound the FilterValue property to a text column. When this column is update, I expected the PCF to update and filter based on the new value. However, I have to save and refresh the form in order for the PCF to update.

-Refreshing the data and form programmatically via JS does not work
-Neither updating the FilterValue column value manually nor programmatically works
-Calling fireOnChange programmatically also does not work

My inexperience with PCFs is likely to blame here but my Googling has not dug up a solution.

**Comment by BenediktBergmann** [comment]
Thanks for reporting the issue, @hew2702. I will take a look at it tomorrow.

**Comment by BenediktBergmann** [comment]
@hew2702 Sorry for the very late response. I somehow forgot about this issue.

I just rechecked and the problem was that I only loaded the FilterValue in the init function (when the PCF gets loaded), but not in the "updateView" (which will be called whenever any property changes). This is now fixed and will come with the next version. There is another issue I would like to fix before I bundle a new version. But this should be done soon and you can expect a new version in a few days.

**Comment by hew2702** [comment]
No worries, thank you so much once again!

**Comment by BenediktBergmann** [comment]
@hew2702 This is implemented and released in version 2.2.1.0
